version: '3.1'
 
services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - redis
    command: redis:6379 db:1433
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"